spring:

  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 0