apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: false
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo


  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki'
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus


  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      derivedFields:
        -   datasourceUid: tempo
            matcherRegex: \[([a-f0-9]{16,32})\]
            name: TraceID
            url: $${__value.raw}


  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope
    access: proxy
    orgId: 1
    url: http://pyroscope:4040
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      httpMethod: POST


  - name: Kafka
    type: hamedkarbasi93-kafka-datasource
    uid: kafka
    access: proxy
    orgId: 1
    url: http://kafka:9092
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      bootstrapServers: kafka:9092
      securityProtocol: PLAINTEXT
      logLevel: info
      healthcheckTimeout: 2000


  - name: Redis
    type: redis-datasource
    uid: redis
    access: proxy
    orgId: 1
    url: redis://redis:6379
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      client: grafana-redis-datasource
      address: redis://redis:6379


  - name: Elasticsearch
    type: elasticsearch
    uid: elasticsearch
    access: proxy
    orgId: 1
    url: http://elasticsearch:9200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      esVersion: "8.0.0"
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: level


  - name: PostgreSQL - Auth
    type: postgres
    uid: postgres-auth
    access: proxy
    orgId: 1
    url: auth-db:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: auth_db
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: false


  - name: PostgreSQL - User
    type: postgres
    uid: postgres-user
    access: proxy
    orgId: 1
    url: user-db:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: user_db
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: false


  - name: PostgreSQL - Notification
    type: postgres
    uid: postgres-notification
    access: proxy
    orgId: 1
    url: notification-db:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: notification_db
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: false


  - name: PostgreSQL - Title
    type: postgres
    uid: postgres-title
    access: proxy
    orgId: 1
    url: title-db:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: title_db
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: false


  - name: PostgreSQL - People
    type: postgres
    uid: postgres-people
    access: proxy
    orgId: 1
    url: people-db:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: people_db
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: false


  - name: PostgreSQL - Ratings & Reviews
    type: postgres
    uid: postgres-ratings-reviews
    access: proxy
    orgId: 1
    url: ratings-reviews-db:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: ratings_reviews_db
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: false


  - name: PostgreSQL - Lists
    type: postgres
    uid: postgres-lists
    access: proxy
    orgId: 1
    url: lists-db:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: lists_db
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: false


  - name: PostgreSQL - Media
    type: postgres
    uid: postgres-media
    access: proxy
    orgId: 1
    url: media-db:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: media_db
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: false


  - name: PostgreSQL - News
    type: postgres
    uid: postgres-news
    access: proxy
    orgId: 1
    url: news-db:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: news_db
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: false


  - name: PostgreSQL - Awards
    type: postgres
    uid: postgres-awards
    access: proxy
    orgId: 1
    url: awards-db:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: awards_db
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: false


  - name: PostgreSQL - Contribution
    type: postgres
    uid: postgres-contribution
    access: proxy
    orgId: 1
    url: contribution-db:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: contribution_db
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: false
