import { PersonDetail } from '../../models/person.model';
import { IMAGES } from './images.mock';

export const MOCK_PEOPLE: PersonDetail[] = [
  {
    id: 'p1',
    name: 'Elena Marchetti',
    slug: 'elena-marchetti',
    alsoKnownAs: ['E. Marchetti', 'Elena M.'],
    biography:
      'Elena Marchetti is an acclaimed actress known for her transformative performances in science fiction and drama. Born in a small coastal town, she began her career in independent theatre before breaking into film. Her portrayal of Commander Vela in Void Voyager earned her international recognition and a place among the genre\u2019s most lauded performers.',
    profileUrl: IMAGES.avatar1,
    birthDate: '1985-06-14',
    deathDate: null,
    birthPlace: 'Naples, Italy',
    gender: 'Female',
    heightCm: 168,
    popularity: 92.4,
    imdbId: 'nm0012345',
    filmography: [
      {
        titleId: 't1',
        primaryTitle: 'Void Voyager',
        posterUrl: IMAGES.poster2,
        titleType: 'MOVIE',
        characterName: 'Commander Vela',
        department: 'Acting',
        job: 'Actress',
        releaseDate: '2023-05-12',
      },
      {
        titleId: 't2',
        primaryTitle: 'Nightfall Protocol',
        posterUrl: IMAGES.poster1,
        titleType: 'MOVIE',
        characterName: 'Det. Holloway',
        department: 'Acting',
        job: 'Actress',
        releaseDate: '2024-03-01',
      },
    ],
  },
  {
    id: 'p2',
    name: 'Darius Kane',
    slug: 'darius-kane',
    alsoKnownAs: [],
    biography:
      'Darius Kane is a versatile actor celebrated for anchoring cerebral thrillers and sci-fi epics with a grounded intensity. His deep, commanding presence has made him a favorite among directors of moody, high-concept cinema.',
    profileUrl: IMAGES.avatar2,
    birthDate: '1978-11-02',
    deathDate: null,
    birthPlace: 'Detroit, Michigan',
    gender: 'Male',
    heightCm: 188,
    popularity: 89.7,
    imdbId: 'nm0056789',
    filmography: [
      {
        titleId: 't1',
        primaryTitle: 'Void Voyager',
        posterUrl: IMAGES.poster2,
        titleType: 'MOVIE',
        characterName: 'Dr. Orion',
        department: 'Acting',
        job: 'Actor',
        releaseDate: '2023-05-12',
      },
      {
        titleId: 't2',
        primaryTitle: 'Nightfall Protocol',
        posterUrl: IMAGES.poster1,
        titleType: 'MOVIE',
        characterName: 'Chief Graves',
        department: 'Acting',
        job: 'Actor',
        releaseDate: '2024-03-01',
      },
    ],
  },
  {
    id: 'p3',
    name: 'Sofia Reyes',
    slug: 'sofia-reyes',
    alsoKnownAs: [],
    biography:
      'Sofia Reyes is a rising star whose breakout performance brought a fresh, magnetic energy to the ensemble of Void Voyager. She splits her time between film and prestige television.',
    profileUrl: IMAGES.avatar3,
    birthDate: '1993-03-20',
    deathDate: null,
    birthPlace: 'Mexico City, Mexico',
    gender: 'Female',
    heightCm: 165,
    popularity: 84.1,
    imdbId: 'nm0098765',
    filmography: [
      {
        titleId: 't1',
        primaryTitle: 'Void Voyager',
        posterUrl: IMAGES.poster2,
        titleType: 'MOVIE',
        characterName: 'Lt. Nya',
        department: 'Acting',
        job: 'Actress',
        releaseDate: '2023-05-12',
      },
    ],
  },
  {
    id: 'p4',
    name: 'Marcus Bell',
    slug: 'marcus-bell',
    alsoKnownAs: [],
    biography:
      'Marcus Bell is an award-winning director and occasional actor whose visual style is defined by high contrast and immersive world-building. He directed the acclaimed sci-fi epic Void Voyager.',
    profileUrl: IMAGES.avatar4,
    birthDate: '1971-08-08',
    deathDate: null,
    birthPlace: 'London, England',
    gender: 'Male',
    heightCm: 181,
    popularity: 87.9,
    imdbId: 'nm0034567',
    filmography: [
      {
        titleId: 't1',
        primaryTitle: 'Void Voyager',
        posterUrl: IMAGES.poster2,
        titleType: 'MOVIE',
        characterName: '',
        department: 'Directing',
        job: 'Director',
        releaseDate: '2023-05-12',
      },
    ],
  },
  {
    id: 'p5',
    name: 'Ingrid Vance',
    slug: 'ingrid-vance',
    alsoKnownAs: [],
    biography:
      'Ingrid Vance is a screenwriter and director celebrated for her razor-sharp dialogue and morally complex characters. She has helmed both the detective thriller Nightfall Protocol and the hit series Crown of Thorns.',
    profileUrl: IMAGES.avatar1,
    birthDate: '1981-01-25',
    deathDate: null,
    birthPlace: 'Oslo, Norway',
    gender: 'Female',
    heightCm: 172,
    popularity: 82.3,
    imdbId: 'nm0065432',
    filmography: [
      {
        titleId: 't2',
        primaryTitle: 'Nightfall Protocol',
        posterUrl: IMAGES.poster1,
        titleType: 'MOVIE',
        characterName: '',
        department: 'Directing',
        job: 'Director',
        releaseDate: '2024-03-01',
      },
      {
        titleId: 's2',
        primaryTitle: 'Crown of Thorns',
        posterUrl: IMAGES.poster5,
        titleType: 'TV_SERIES',
        characterName: '',
        department: 'Writing',
        job: 'Writer',
        releaseDate: '2021-07-15',
      },
    ],
  },
];
