import { CastMember, CrewMember, Movie, TvShow } from '../../models/title.model';
import { IMAGES } from './images.mock';

export const MOCK_MOVIES: Movie[] = [
  {
    id: 't1',
    titleType: 'MOVIE',
    primaryTitle: 'Void Voyager',
    originalTitle: 'Void Voyager',
    slug: 'void-voyager',
    tagline: 'Somewhere between stars and silence.',
    overview:
      'In a distant future, a group of deep-space explorers aboard the starship Aether discovers an anomaly that could unravel the fabric of reality itself. As their vessel drifts toward a golden star at the edge of the known universe, the crew must confront the terrifying truth that they may not be alone—and that their mission may have a purpose far beyond anything they imagined.',
    posterUrl: IMAGES.poster2,
    backdropUrl: IMAGES.hero,
    status: 'RELEASED',
    releaseDate: '2023-05-12',
    runtimeMins: 148,
    budget: 185000000,
    revenue: 452800000,
    imdbRating: 9.1,
    voteCount: 512340,
    popularity: 98.4,
    adult: false,
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    languages: ['English'],
    countries: ['United States'],
    boxOffice: {
      budget: 185000000,
      openingWeekend: 68400000,
      domestic: 201300000,
      international: 251500000,
      worldwide: 452800000,
      currency: 'USD',
    },
    trailers: [
      {
        id: 'tr1',
        name: 'Official Trailer',
        trailerType: 'Trailer',
        youtubeKey: 'd9MyW72ELq0',
        durationSecs: 152,
        language: 'English',
        publishedAt: '2023-02-10',
      },
    ],
  },
  {
    id: 't2',
    primaryTitle: 'Nightfall Protocol',
    originalTitle: 'Nightfall Protocol',
    slug: 'nightfall-protocol',
    titleType: 'MOVIE',
    tagline: 'In the rain, secrets surface.',
    overview:
      'A gritty detective drama set in a rainy London, where a shadowed detective hunts a phantom killer whose crimes are staged to mirror the city\u2019s oldest unsolved case. With neon reflections bleeding across wet pavement, every clue pulls him deeper into a conspiracy that reaches the highest towers of power.',
    posterUrl: IMAGES.poster1,
    backdropUrl: IMAGES.hero,
    status: 'RELEASED',
    releaseDate: '2024-03-01',
    runtimeMins: 132,
    budget: 72000000,
    revenue: 128500000,
    imdbRating: 8.4,
    voteCount: 288410,
    popularity: 87.2,
    adult: false,
    genres: ['Thriller', 'Crime', 'Mystery'],
    languages: ['English'],
    countries: ['United Kingdom'],
    boxOffice: {
      budget: 72000000,
      openingWeekend: 21400000,
      domestic: 56300000,
      international: 72200000,
      worldwide: 128500000,
      currency: 'USD',
    },
    trailers: [
      {
        id: 'tr2',
        name: 'Official Trailer',
        trailerType: 'Trailer',
        youtubeKey: 'Ti2m-8mAFgA',
        durationSecs: 138,
        language: 'English',
        publishedAt: '2024-01-15',
      },
    ],
  },
  {
    id: 't3',
    primaryTitle: 'Shattered Mirror',
    originalTitle: 'Shattered Mirror',
    slug: 'shattered-mirror',
    titleType: 'MOVIE',
    tagline: 'Every reflection hides a truth.',
    overview:
      'A psychological thriller following a brilliant psychiatrist who begins seeing her own face in the memories of a catatonic patient. As the line between reality and delusion blurs, a shattered mirror effect distorts everything she thought she knew about herself, forcing a confrontation with a past she buried long ago.',
    posterUrl: IMAGES.poster3,
    backdropUrl: IMAGES.hero,
    status: 'RELEASED',
    releaseDate: '2024-07-19',
    runtimeMins: 119,
    budget: 45000000,
    revenue: 88600000,
    imdbRating: 7.8,
    voteCount: 194320,
    popularity: 79.6,
    adult: false,
    genres: ['Thriller', 'Drama', 'Horror'],
    languages: ['English'],
    countries: ['United States'],
    boxOffice: {
      budget: 45000000,
      openingWeekend: 15200000,
      domestic: 39400000,
      international: 49200000,
      worldwide: 88600000,
      currency: 'USD',
    },
    trailers: [
      {
        id: 'tr3',
        name: 'Official Trailer',
        trailerType: 'Trailer',
        youtubeKey: 'Z4jHvJ8iPqY',
        durationSecs: 142,
        language: 'English',
        publishedAt: '2024-05-20',
      },
    ],
  },
  {
    id: 't4',
    primaryTitle: 'Robot in the Reed',
    originalTitle: 'Robot in the Reed',
    slug: 'robot-in-the-reed',
    titleType: 'MOVIE',
    tagline: 'A friendship blooms in the wild.',
    overview:
      'An animated adventure following a curious robotic explorer who wakes up in a lush, bioluminescent jungle and befriends a shy woodland creature. Together they set off to uncover why the lights of the forest are fading, in a visual feast of glowing flora and heartfelt discovery.',
    posterUrl: IMAGES.poster4,
    backdropUrl: IMAGES.hero,
    status: 'RELEASED',
    releaseDate: '2024-04-05',
    runtimeMins: 104,
    budget: 90000000,
    revenue: 241000000,
    imdbRating: 8.2,
    voteCount: 146780,
    popularity: 84.0,
    adult: false,
    genres: ['Animation', 'Adventure', 'Family'],
    languages: ['English'],
    countries: ['United States'],
    boxOffice: {
      budget: 90000000,
      openingWeekend: 33800000,
      domestic: 112000000,
      international: 129000000,
      worldwide: 241000000,
      currency: 'USD',
    },
    trailers: [
      {
        id: 'tr4',
        name: 'Official Trailer',
        trailerType: 'Trailer',
        youtubeKey: 'qH48uSje3Wc',
        durationSecs: 126,
        language: 'English',
        publishedAt: '2024-02-28',
      },
    ],
  },
  {
    id: 't5',
    primaryTitle: 'Sands of Empire',
    originalTitle: 'Sands of Empire',
    slug: 'sands-of-empire',
    titleType: 'MOVIE',
    tagline: 'An empire rises from the dust.',
    overview:
      'A sweeping historical epic set in a vast desert at sunset, where a caravan of exiles stumbles upon the last remnants of a fallen empire. As a burning orange sun dips below the horizon, their leader must decide whether to rebuild the old world or forge a new one from the ashes.',
    posterUrl: IMAGES.poster5,
    backdropUrl: IMAGES.hero,
    status: 'RELEASED',
    releaseDate: '2024-09-13',
    runtimeMins: 172,
    budget: 210000000,
    revenue: 389200000,
    imdbRating: 8.9,
    voteCount: 402110,
    popularity: 93.1,
    adult: false,
    genres: ['Drama', 'Adventure', 'History'],
    languages: ['English'],
    countries: ['United States', 'Morocco'],
    boxOffice: {
      budget: 210000000,
      openingWeekend: 79300000,
      domestic: 186500000,
      international: 202700000,
      worldwide: 389200000,
      currency: 'USD',
    },
    trailers: [
      {
        id: 'tr5',
        name: 'Official Trailer',
        trailerType: 'Trailer',
        youtubeKey: 'rJ7wJwKmnPs',
        durationSecs: 165,
        language: 'English',
        publishedAt: '2024-08-01',
      },
    ],
  },
  {
    id: 't6',
    primaryTitle: 'Velocity Zero',
    originalTitle: 'Velocity Zero',
    slug: 'velocity-zero',
    titleType: 'MOVIE',
    tagline: 'Speed is survival.',
    overview:
      'A high-octane racing thriller centered on an underground circuit where drivers risk everything for a shot at redemption. Blurred streaks of red and white lights cut through the dark asphalt as a sleek black prototype car and its troubled driver take on a corrupt racing empire.',
    posterUrl: IMAGES.poster6,
    backdropUrl: IMAGES.hero,
    status: 'RELEASED',
    releaseDate: '2023-11-10',
    runtimeMins: 126,
    budget: 88000000,
    revenue: 164300000,
    imdbRating: 7.5,
    voteCount: 120450,
    popularity: 76.8,
    adult: false,
    genres: ['Action', 'Thriller', 'Sports'],
    languages: ['English'],
    countries: ['United States'],
    boxOffice: {
      budget: 88000000,
      openingWeekend: 24800000,
      domestic: 67900000,
      international: 96400000,
      worldwide: 164300000,
      currency: 'USD',
    },
    trailers: [
      {
        id: 'tr6',
        name: 'Official Trailer',
        trailerType: 'Trailer',
        youtubeKey: 'oY1HHv1MvPk',
        durationSecs: 133,
        language: 'English',
        publishedAt: '2023-09-15',
      },
    ],
  },
  {
    id: 't7',
    primaryTitle: 'The Silent North',
    originalTitle: 'The Silent North',
    slug: 'the-silent-north',
    titleType: 'MOVIE',
    tagline: "Nature's quiet is the loudest.",
    overview:
      'A prestige drama following a hermit living alone in a snowy pine forest at twilight, whose carefully constructed solitude is shattered by the arrival of a lost city journalist. As the soft blue light of the snow contrasts with the warm orange glow of his cabin, an unlikely friendship forces both men to confront the reasons they ran.',
    posterUrl: IMAGES.poster1,
    backdropUrl: IMAGES.fan1,
    status: 'RELEASED',
    releaseDate: '2022-12-02',
    runtimeMins: 141,
    budget: 38000000,
    revenue: 97500000,
    imdbRating: 9.4,
    voteCount: 612230,
    popularity: 90.5,
    adult: false,
    genres: ['Drama'],
    languages: ['English'],
    countries: ['Canada'],
    boxOffice: {
      budget: 38000000,
      openingWeekend: 8400000,
      domestic: 41200000,
      international: 56300000,
      worldwide: 97500000,
      currency: 'USD',
    },
    trailers: [
      {
        id: 'tr7',
        name: 'Trailer',
        trailerType: 'Trailer',
        youtubeKey: 'C5oOw3xQrrA',
        durationSecs: 148,
        language: 'English',
        publishedAt: '2022-10-12',
      },
    ],
  },
  {
    id: 't8',
    primaryTitle: 'Beyond the Curtain',
    originalTitle: 'Beyond the Curtain',
    slug: 'beyond-the-curtain',
    titleType: 'MOVIE',
    tagline: 'The show must go on.',
    overview:
      'Set in 1940s classic Hollywood, this romantic drama follows an aging starlet who discovers that the biggest role of her life is the one she refuses to play. With dramatic shadows and bright highlights casting a timeless glow, it is a love letter to the golden age of cinema.',
    posterUrl: IMAGES.poster3,
    backdropUrl: IMAGES.hero,
    status: 'RELEASED',
    releaseDate: '2021-06-18',
    runtimeMins: 128,
    budget: 41000000,
    revenue: 78200000,
    imdbRating: 8.1,
    voteCount: 98760,
    popularity: 71.3,
    adult: false,
    genres: ['Drama', 'Romance'],
    languages: ['English'],
    countries: ['United States'],
    boxOffice: {
      budget: 41000000,
      openingWeekend: 9600000,
      domestic: 38400000,
      international: 39800000,
      worldwide: 78200000,
      currency: 'USD',
    },
    trailers: [
      {
        id: 'tr8',
        name: 'Teaser',
        trailerType: 'Teaser',
        youtubeKey: 'bFyXlWjPm2Q',
        durationSecs: 96,
        language: 'English',
        publishedAt: '2021-04-05',
      },
    ],
  },
];

export const MOCK_TV_SHOWS: TvShow[] = [
  {
    id: 's1',
    titleType: 'TV_SERIES',
    primaryTitle: 'The Neon Divide',
    originalTitle: 'The Neon Divide',
    slug: 'the-neon-divide',
    tagline: 'Two cities. One truth.',
    overview:
      'Set in a futuristic metropolis torn between a gleaming corporate arcology and the rain-slicked neon undercity below, this series follows two siblings on opposite sides of a violent divide. As their worlds collide, they uncover a conspiracy that threatens to erase the border between them entirely.',
    posterUrl: IMAGES.poster2,
    backdropUrl: IMAGES.hero,
    status: 'RELEASED',
    releaseDate: '2022-01-21',
    runtimeMins: 0,
    budget: 0,
    revenue: 0,
    imdbRating: 8.7,
    voteCount: 354120,
    popularity: 95.6,
    adult: false,
    genres: ['Sci-Fi', 'Drama', 'Thriller'],
    languages: ['English'],
    countries: ['United States'],
    network: 'StreamPrime',
    creatorId: 'p4',
    totalSeasons: 3,
    totalEpisodes: 28,
    episodeRuntime: 52,
    isOnGoing: true,
    seasons: [
      {
        id: 'se1',
        seasonNumber: 1,
        title: 'Season 1',
        overview: 'The siblings meet after a decade apart.',
        posterUrl: IMAGES.poster2,
        airDate: '2022-01-21',
        episodes: [
          {
            id: 'e1',
            episodeNumber: 1,
            title: 'Pilot',
            overview: 'Two siblings are reunited across the divide.',
            stillUrl: IMAGES.hero,
            airDate: '2022-01-21',
            runtimeMins: 55,
            imdbRating: 8.4,
            voteCount: 12000,
          },
          {
            id: 'e2',
            episodeNumber: 2,
            title: 'Fault Lines',
            overview: 'The conspiracy begins to surface.',
            stillUrl: IMAGES.hero,
            airDate: '2022-01-28',
            runtimeMins: 50,
            imdbRating: 8.6,
            voteCount: 10900,
          },
        ],
      },
      {
        id: 'se2',
        seasonNumber: 2,
        title: 'Season 2',
        overview: 'The divide threatens to break.',
        posterUrl: IMAGES.poster2,
        airDate: '2023-02-10',
        episodes: [
          {
            id: 'e3',
            episodeNumber: 1,
            title: 'Aftermath',
            overview: 'A fragile peace is tested.',
            stillUrl: IMAGES.hero,
            airDate: '2023-02-10',
            runtimeMins: 54,
            imdbRating: 8.8,
            voteCount: 9800,
          },
        ],
      },
    ],
  },
  {
    id: 's2',
    titleType: 'TV_SERIES',
    primaryTitle: 'Crown of Thorns',
    originalTitle: 'Crown of Thorns',
    slug: 'crown-of-thorns',
    tagline: 'Power comes at a price.',
    overview:
      'A medieval political drama chronicling the brutal rise of a peasant girl who becomes queen of a fractured kingdom. Loyalty, betrayal, and war shape a reign built on blood and sacrifice as she fights to keep the crown she never wanted.',
    posterUrl: IMAGES.poster5,
    backdropUrl: IMAGES.hero,
    status: 'RELEASED',
    releaseDate: '2021-07-15',
    runtimeMins: 0,
    budget: 0,
    revenue: 0,
    imdbRating: 8.3,
    voteCount: 210650,
    popularity: 81.4,
    adult: false,
    genres: ['Drama', 'History', 'Action'],
    languages: ['English'],
    countries: ['United Kingdom'],
    network: 'BroadcastOne',
    creatorId: 'p5',
    totalSeasons: 4,
    totalEpisodes: 40,
    episodeRuntime: 58,
    isOnGoing: true,
    seasons: [
      {
        id: 'se3',
        seasonNumber: 1,
        title: 'Season 1',
        overview: 'A peasant girl rises.',
        posterUrl: IMAGES.poster5,
        airDate: '2021-07-15',
        episodes: [
          {
            id: 'e4',
            episodeNumber: 1,
            title: 'The Rise',
            overview: 'She escapes the village.',
            stillUrl: IMAGES.hero,
            airDate: '2021-07-15',
            runtimeMins: 60,
            imdbRating: 8.1,
            voteCount: 8900,
          },
        ],
      },
    ],
  },
];

export const MOCK_CAST: Record<string, CastMember[]> = {
  t1: [
    {
      personId: 'p1',
      name: 'Elena Marchetti',
      slug: 'elena-marchetti',
      characterName: 'Commander Vela',
      profileUrl: IMAGES.avatar1,
      billingOrder: 1,
      isVoice: false,
      episodeCount: 1,
    },
    {
      personId: 'p2',
      name: 'Darius Kane',
      slug: 'darius-kane',
      characterName: 'Dr. Orion',
      profileUrl: IMAGES.avatar2,
      billingOrder: 2,
      isVoice: false,
      episodeCount: 1,
    },
    {
      personId: 'p3',
      name: 'Sofia Reyes',
      slug: 'sofia-reyes',
      characterName: 'Lt. Nya',
      profileUrl: IMAGES.avatar3,
      billingOrder: 3,
      isVoice: false,
      episodeCount: 1,
    },
    {
      personId: 'p4',
      name: 'Marcus Bell',
      slug: 'marcus-bell',
      characterName: 'Engineer Kai',
      profileUrl: IMAGES.avatar4,
      billingOrder: 4,
      isVoice: false,
      episodeCount: 1,
    },
  ],
  t2: [
    {
      personId: 'p1',
      name: 'Elena Marchetti',
      slug: 'elena-marchetti',
      characterName: 'Det. Holloway',
      profileUrl: IMAGES.avatar1,
      billingOrder: 1,
      isVoice: false,
      episodeCount: 1,
    },
    {
      personId: 'p2',
      name: 'Darius Kane',
      slug: 'darius-kane',
      characterName: 'Chief Graves',
      profileUrl: IMAGES.avatar2,
      billingOrder: 2,
      isVoice: false,
      episodeCount: 1,
    },
  ],
};

export const MOCK_CREW: Record<string, CrewMember[]> = {
  t1: [
    {
      personId: 'p4',
      name: 'Marcus Bell',
      slug: 'marcus-bell',
      department: 'Directing',
      job: 'Director',
      profileUrl: IMAGES.avatar4,
    },
    {
      personId: 'p5',
      name: 'Ingrid Vance',
      slug: 'ingrid-vance',
      department: 'Writing',
      job: 'Writer',
      profileUrl: IMAGES.avatar1,
    },
  ],
  t2: [
    {
      personId: 'p5',
      name: 'Ingrid Vance',
      slug: 'ingrid-vance',
      department: 'Directing',
      job: 'Director',
      profileUrl: IMAGES.avatar1,
    },
  ],
};
