spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

management:
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://tempo:4318/v1/traces