spring:

  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    consumer:
      group-id: notification_service

  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  brand-name: IMDb Clone
  support-email: support@imdbclone.com
  base-url: http://localhost:8080

email:
  provider: MOCK

server:
  port: 9092
